### ISSUE TITLE
List of known `sourcemap inject` bugs

### ISSUE THREAD

**Issue by loewenheim** [getsentry/sentry-cli#1647]
1. We have gotten customer reports of injection problems when a file starts with something like

```js
(this.foo=this.bar||[]).push([[2],[function(e,t,n){"use strict"; […] }
```

This trips the "use pragma" detection and causes the line to be skipped, which is obviously not intended. Solution: make the regex stricter.

2. Block comments aren't handled at all. Thus, if a file started with

```js
/* lol, lmao */
"use strict";
```
we would erroneously inject at the very top. Solution: handle block comments.

3. `'use strict';` can be on the same line as the rest of the code, eg `'use strict';(function(){console.log('wat')})();` is a valid code, and we do not handle injecting snippet "in-between" - ref: https://github.com/getsentry/sentry-cli/issues/1646

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-cli/pull/1648
- [x] Handle block comments
- [x] Handle same-line `use strict` usages
```

**Comment by yharaskrik** [comment]
I have something to add to this list. We are using GraphQL and sometimes the injection gets injected into the template string that is defining out GraphQL queries. Here is a couple snippets to show you:

![image](https://github.com/getsentry/sentry-cli/assets/9469090/19f37388-197e-4e24-861c-e84b977b69a0)
![image](https://github.com/getsentry/sentry-cli/assets/9469090/432e0718-00c5-4e5a-b626-395b50354b66)
Although this MIGHT fall into #1 above.

**Comment by loewenheim** [comment]
Thank you for the report. The second screenshot looks gnarly. The fact that a statement starts on the same line as the pragma and then continues for several lines is going to be very hard to work around.

**Comment by yharaskrik** [comment]
> Thank you for the report. The second screenshot looks gnarly. The fact that a statement starts on the same line as the pragma and then continues for several lines is going to be very hard to work around.

Is that not normal? I don't think we are doing anything different than a normal Angular production build. I can investigate a bit to see if maybe we are doing something out of the norm?

**Comment by yharaskrik** [comment]
> > Is that not normal? I don't think we are doing anything different than a normal Angular production build. I can investigate a bit to see if maybe we are doing something out of the norm?
> 
> Sorry, I didn't mean to imply you were doing anything wrong. This is just one of several assumptions we were making that appear to not hold up in practice.

No worries all good! I can double check that a plain angular build that is freshly generated does the same thing just so we know.

**Comment by yharaskrik** [comment]
> > > Is that not normal? I don't think we are doing anything different than a normal Angular production build. I can investigate a bit to see if maybe we are doing something out of the norm?
> > 
> > 
> > Sorry, I didn't mean to imply you were doing anything wrong. This is just one of several assumptions we were making that appear to not hold up in practice.
> 
> No worries all good! I can double check that a plain angular build that is freshly generated does the same thing just so we know.


Just generate a fresh Angular project using Nx, looks like the apps get minified to a single line. So ya. I guess that is a case you might have to handle. Let me know if I can help at all.

**Comment by j-fulbright** [comment]
We are seeing issues with inject breaking our sourcemaps with the debug id injection (Angular Production build). 

The resulting sourcemap does not properly map and is treated as if there is an extra line in most cases. 

It appears that injecting the debug id causes it to rewrite the header for the sourcemap, as well:

![image](https://github.com/getsentry/sentry-cli/assets/10793868/d1bccc19-6576-400f-9740-c06c198a7103)

![image](https://github.com/getsentry/sentry-cli/assets/10793868/eb466671-eb93-4fa3-befe-5f7783593472)

Original Sourcemap:
![image](https://github.com/getsentry/sentry-cli/assets/10793868/01231201-1537-4c8c-bd17-e60b1f3d2f2d)

Injected Sourcemap:
![image](https://github.com/getsentry/sentry-cli/assets/10793868/77c4adfa-88b5-4457-9e52-19ec7a85f2f5)

**Comment by loewenheim** [comment]
@j-fulbright Does the first line of the injected JS file contain `"use strict";` or something similar?

**Comment by j-fulbright** [comment]
Actually after reviewing with another developer, it was determined the CLI is adding an extraneous semicolon in the mappings group. 

Working:
```
{"version":3,"file":"main.2de0db9ef2b6b37e.js","mappings":"uIAAO
```

After CLI:
```
"file":"main.2de0db9ef2b6b37e.js","mappings":";uIAAO,IAAMA
```

This is breaking it all for us, removing the semicolon fixes it.

**Comment by d3ce1t** [comment]
I'm executing this in a React App in order to remove the semicolon in sourcemaps after injecting debugIds using sentry-cli:

`find build/static/js -type f -name "*.js.map" -exec sed -i 's/\("mappings":"\);/\1/g' {} +`

I hope it works for you :)

**Comment by loewenheim** [comment]
I am sorry for the frustration caused by this. We're currently working on putting injection on a more solid foundation.

**Comment by kamilogorek** [comment]
Adding https://github.com/getsentry/sentry-cli/issues/1689 to the list to make it easier to track.

**Comment by kamilogorek** [comment]
Yes, sorry. Thanks for catching this. I meant to close linked issue only 😅

**Comment by loewenheim** [comment]
All of these bugs should be fixed as of `sentry-cli 2.20.4`. Thank you very much for your forbearance, eveyone 🙇

**Comment by NSiggel** [comment]
not sure if related, but we are having an issue where using "sentry-cli sourcemaps inject" has broken our projects use of the Angular SwUpdate.versionUpdates.subscribe((event: VersionEvent)
to run automatic updates in our application in production.

As soon as we removed the 
- sentry-cli sourcemaps inject $CODEBUILD_SRC_DIR/www

The next release went through automatic updates properly.

I suspect this is causing an issue for the ServiceWorker process looking up which files need to be downloaded (hashmap lookup ?) such that the inject process breaks the hashmap of files to be downloaded by the updater ?

ANY suggestions/work arounds ? I was happy to finally get proper source maps for a release working w/ Web/iOS Capacitor via the artifact bundles but now need to remove it from our CICD since broke automatic updates.

**Comment by lforst** [comment]
@NSiggel To me this doesn't sound like a bug. If injecting something into your code is not feasible due to code integrity you should probably resort to the [legacy method of uploading](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/legacy-uploading-methods) which does not need to inject but is a bit trickier to get right.

If you face any more issues please open another issue since this seems unrelated.
