### ISSUE TITLE
Rework debug id injection

### ISSUE THREAD

**Issue by loewenheim** [getsentry/sentry-cli#1670]
Injection is [incredibly buggy](https://github.com/getsentry/sentry-cli/issues/1647), mostly because we only inject at a line boundary, even though sometimes the correct place is in the middle of a line. This creates frustration for users and hurts debug id adoption. Splitting lines apart would mean we would need to edit the sourcemap in a nontrivial way, however.

A possible way forward—my preferred option, if it works out the way I imagine it—is as follows.
1. Use the Rust port of `magic-string` to inject in exactly the right place and generate a sourcemap from the injected file to the pre-injected one. In my preliminary tests this works nicely.
2. Add a composition operation to `rust-sourcemap`. Given a sourcemap `ab.map` from file `a` to file `b` and a sourcemap `bc.map` from file `b` to files `c₁, …, cₙ`, this would produce a sourcemap `ac.map` from `a` to `c₁, …, cₙ` by composing the mappings from `ab.map` and `bc.map`.
3. Compose the sourcemap obtained in (1) with the one we already have to obtain a correct sourcemap from the injected file to the unminified files.

```[tasklist]
### Tasks
- [x] (by 2023-07-28) https://github.com/getsentry/sentry-cli/pull/1693
- [x] (by 2023-08-04) https://github.com/getsentry/rust-sourcemap/pull/67
- [x] (by 2023-08-11) Integrate the previous two items into a corerct injection procedure (see 1)
- [ ] https://github.com/getsentry/publish/issues/2575
```
