### ISSUE TITLE
Improved issue creation flow

### ISSUE THREAD

**Issue by szokeasaurusrex** [getsentry/sentry-cli#2036]
We should improve the issue creation flow in this repository to ensure that people who open issues provide all the information we need to triage and investigate their problems upfront.

These improvements can be implemented by switching from using issue templates to issue forms, and by hiding the "blank issue" link. The specific changes are broken down below:

### Tasks

- [ ] [https://github.com/getsentry/sentry-cli/issues/2037](https://github.com/getsentry/sentry-cli/issues/2037)
- [ ] [https://github.com/getsentry/sentry-cli/issues/2038](https://github.com/getsentry/sentry-cli/issues/2038)
- [ ] Hide "blank issue" link
